### ISSUE TITLE
How does singing on client side makes user available on server side automatically in auth-helper?

### ISSUE THREAD

**Issue by roker15** [supabase/auth-helpers#321]
I see we get user server side in nextjs by 
```
export default async (req: NextApiRequest, res: NextApiResponse) => {
  const supabaseServerClient = createServerSupabaseClient<Database>({ req, res })
  
const { data:{ user } } = await supabaseServerClient.auth.getUser()

}
```
I want to know how user is automatically available here? 

1. I never set **user** server side while signing client side. 
2. Also i never used `onAuthStateChange` client side
3. I never set any supabase **cookies** in **req** object sent to next js API route

**Comment by roker15** [comment]
> Does that help clarify?

Thanks, well explained

**Comment by david-plugge** [comment]
I think you are better of asking questions like this on the supabase discord server.

Feel free to close this issue if it´s resolved :)

**Comment by rphlmr** [comment]
Hello @thorwebdev 

I read the code and something trigger me.
The cookie is not httpOnly (so, redable client side by any js script).
Is it not vulnerable to an XSS attack?

I know this is done to allow to share of auth session between the browser and the server.

I you work in Europe, I guess this is something that GDPR could complain about in case of stolen data :/

**Comment by hf** [comment]
Hi @rphlmr,

I'm on the Supabase Auth team and would like to provide some answers to your questions and concerns.

> The cookie is not httpOnly (so, redable client side by any js script). 

Yes, this is intended behavior. The client-side application is still an interactive application that can and should refresh a session as it's being used. It has to have read/write access to the cookies for this to work. 

HTTP-Only cookies only work with static applications where there's virtually no dynamic JavaScript on the served HTML content, or where the HTML content only communicates with one domain (your application's domain). When the HTML content talks to third-party APIs, managing HTTP-Only cookies becomes a very error-prone experience, and is thus not widely used in the modern web. (Example: Authorization headers instead of cookies.)

It's not readable by "any js script" due to the [Same-Origin Policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy).

> Is it not vulnerable to an XSS attack?

XSS has nothing to do with cookies. You probably mean CSRF (Cross-Site Request Forgery) and unfortunately when your application's architecture is using APIs as a service, CSRF protection is practically impossible to implement. Supabase Auth is designed to work also in non-browser environments, so CSRF cookies are not something that can be enforced. 

If this is a true concern for your application, it's best to implement a proxy in front of Supabase Auth which will be handling the CSRF binding tokens/cookies. 

Most modern applications, however, use CORS rules to prevent a large number of potential CSRF attacks.

> I you work in Europe, I guess this is something that GDPR could complain about in case of stolen data :/

I don't see how GDPR plays in all of this. The cookie that's passing between the browser and your application's server is done over TLS and the browser's cookie settings do not leak them over to parties your application has not previously approved.

**Comment by rphlmr** [comment]
Thanks, @hf  for your detailed answer.

Before you released this package I built a solution to sync Remix session cookies with the browser's Supabase client (mostly to use real-time).
The idea was to get the session from the root loader and put it in a React Context (with an interval effect based on expires_in to trigger a Remix action and refresh the session).

I maintain a [Remix stack around Supabase and Prisma](https://github.com/rphlmr/supa-fly-stack) and someone ask me if I could "replace" the hand-crafted thing I did, with your package. Because I previously had questions about security concerns, I wanted to be sure how It works 😇 .

I'll consider updating my stack to not scatter people with multiple ways to handle auth in Remix with Supabase.

**Comment by rphlmr** [comment]
One more thing, cookies are vulnerable to XSS when they are not HttpOnly ;)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies

https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#httponly-attribute

**Comment by sannajammeh** [comment]
A good while ago I wrote an article over at [here](https://sannajammeh.com/blog/advanced-authentication-edge-using-supabase-nextjs) on how to use Supabase at the edge. This was before Auth helpers if I recall, also before App dir so it definitely needs some refreshing.

The ideal here would be this:
1. Most endpoints use PKCE grant flow
2. Whatever needs client side auth persists only to LS.
3. We have a custom endpoint only for POST requests receiving a valid token as body
4. Whatever uses client side auth -> sign in, then POST to that endpoint with tokens
5. POST endpoint validates and sets httpOnly cookies
6. Now finally redirect on client side to where-ever you want.

Correct me if I'm wrong but this should work if you only use the "@supabase/supabase-js" in client components. That should only persist to LS.

**Comment by silentworks** [comment]
Closing this out as I believe the original question was answered and the OP was satisfied with the answer.
