### ISSUE TITLE
Local User object not updating

### ISSUE THREAD

**Issue by jagnani73** [supabase/auth-helpers#377]
# Bug report

## Describe the bug

When logging in (creating a local session), a local user object is also instantiated with it, that is fetched via the `useUser` hook. In a case where
- I make the api call of `updateUser` that is update the users metadata, the local object does not get updated and still shows the previous metadata that was there at the time the user object was instantiated
- I refresh the page post updating the metadata, the new metadata is not fetched and it still shows the previous metadata that was there at the time the user object was instantiated

Either a `setUser` function should also be exported from the `useUser` hook, or it should happen automatically (with the help of `onAuthStateChange`)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Log in user supabase
2. Make an API call to update the user

## Expected behavior

The local user data should get updated, but it doesnt, even after a refresh

**Comment by internetmilk** [comment]
It is a very annoying bug that we've also been dealing with. But we found if you call supabaseClient.auth.refreshSession() after updating the user, it corrects the data in the cookie and in the local session memory:

https://supabase.com/docs/reference/javascript/auth-refreshsession

**Comment by thorwebdev** [comment]
This is expected. After updating the user object you would need to issue a new JWT e.g. by calling `refreshSession`. Since the JWT is signed by the Auth server.

In general you can't rely on the user data in the JWT to be up to date. The JWT is solely meant as an authentication mechanism. Therefore if you need guranteed up to date user data, you should call the `supabase.auth.getUser` instead.
