### ISSUE TITLE
The default cookie maxAge is 1000 years

### ISSUE THREAD

**Issue by gutenye** [supabase/auth-helpers#441]
# Bug report

## Describe the bug

This line defines the default maxAge for the cookie 

https://github.com/supabase/auth-helpers/blob/1c07049b29b0dfed414264e31350d3f2224718de/packages/shared/src/supabase-server.ts#L28

The maxAge unit is second (not milliseconds), so that's 1000 years 😱. I think this is a bug, expect one year?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by david-plugge** [comment]
It´s probably not expected as the `1000` comes before all other numbers and therefore should represent the ms.
But as @SaileshBechar mentioned, this isn´t an issue as the access_token has a set lifetime anyway. But we should still correct this mistake, thanks for reporting.

**Comment by hmnd** [comment]
This should not have been closed. Fixed in #765

**Comment by kangmingtay** [comment]
Hi everyone, it's fine for the cookie max-age to be infinite because we use the cookie to store the session (access token) which is a JWT that contains an `exp` claim.

Setting the max-age of the cookie to a value that's less than the `exp` of the JWT can cause weird random logout behaviour because the cookie is removed before supabase auth can refresh the session

**Comment by n-sviridenko** [comment]
Yes, but how you'd justify placing a browser cookie for 1000 years? We still have GDPR and all this stuff.

And there is no way to override it..
