### ISSUE TITLE
Plans to support NextJS 13 Server Actions?

### ISSUE THREAD

**Issue by chitalian** [supabase/auth-helpers#540]
Any plans to support server actions?
https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions

would be great to have

```typescript
  async function addItem(data) {
    "use server";
    new createServerActionSupabaseClient({cookies: cookies()});
  }
```

**Comment by silentworks** [comment]
We are looking into it but at the moment this is an experimental feature and likely to change so we will likely wait until it becomes stable.

**Comment by silentworks** [comment]
Look like I spoke too soon. Since the API is the same as the RouteHandler at the moment it looks like one of my team mate (@dijonmusters) has added in provision for it in the `.next` release which will be made final soon. https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/src/serverActionClient.ts

**Comment by chitalian** [comment]
Thank you!
