### ISSUE TITLE
[Invite user by email] Code Exchange Route doesn't generate Supabase client and session.

### ISSUE THREAD

**Issue by tronxdev** [supabase/auth-helpers#567]
Supabase's instruction I followed is [here](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#code-exchange-route).

In `app/auth/callback/route.ts` file, added the following code snippet.
```ts
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'

import type { NextRequest } from 'next/server'
import type { Database } from '@/lib/database.types'

export async function GET(request: NextRequest) {
  const requestUrl = new URL(request.url)
  const code = requestUrl.searchParams.get('code')

  console.log(`/auth/callback`, code);

  if (code) {
    const supabase = createRouteHandlerClient<Database>({ cookies })
    await supabase.auth.exchangeCodeForSession(code)
  }

  // URL to redirect to after sign in process completes
  return NextResponse.redirect(requestUrl.origin)
}
```

I created a magic link successfully via API. When it was accepted, `code` was found NULL. Therefore, Supabase didn't create its client and generate the session.

**Comment by silentworks** [comment]
Did you follow the steps here with the redirectUrl? https://supabase.com/docs/guides/auth/auth-helpers/nextjs#client-side

**Comment by tronxdev** [comment]
I set the `redirectUrl` in `inviteUserByEmail` method as below:

```ts
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: {
    autoRefreshToken: false,
    persistSession: true,
  },
});

await supabase.auth.admin.inviteUserByEmail(email as string, {
  redirectTo: WEB_URL + "/auth/callback",
});
```

**Comment by silentworks** [comment]
The issue here is you are using two different Supabase clients. You are using the normal `@supabase/supabase-js` and then also using the `@supabase/auth-helpers-nextjs` client. This mix is where the issue is at, you will need to set the `flowType` in the normal `@supabase/supabase-js` type to `pkce` but you will also need to pass it the same cookie storage mechanism that you are using for the `@supabase/auth-helpers-nextjs` client too.

**Comment by silentworks** [comment]
Actually thinking about this more and it won't work that way because the `inviteUserByEmail` would have been triggered by an admin and not the actual user themself. Let me look into this and get back to you.

**Comment by tronxdev** [comment]
@silentworks Any update here?

**Comment by silentworks** [comment]
Yeah when using PKCE you will need to allow the user to use a code instead of the link in the email. I think the invite email template by default has a `{{ .Token }}` variable in it which is the code and you will need to add a link to your endpoint where the user can `.verifyOtp` which would take the user's email and token code.

**Comment by tronxdev** [comment]
@silentworks Does it mean that Supabase doesn't support `inviteUserByEmail`? My project is to invite users by magic link in email. I can't get how to replace this with code from your instruction. Could you please elaborate more for me?

**Comment by tronxdev** [comment]
`inviteUserByEmail` has no option of 6-digit code. Could you please show me how to send 6-digit code for invite using Supabase Email provider?

**Comment by hamishtaplin** [comment]
How are we supposed to work around this limitation in local development? If we can't edit the email template, it's not possible.

**Comment by silentworks** [comment]
@hamishtaplin which issue are you referring to? the default email template in local development has the 6 digit code in it.

**Comment by hamishtaplin** [comment]
@silentworks Yeah the local dev email template. We need to be recreate the production user journey locally in order to develop the feature and write tests against it.

**Comment by silentworks** [comment]
@hamishtaplin we are working on the local dev email templates support at the moment and will have something ready for the general public soon. I've attached a preview video of the PoC.

https://github.com/supabase/auth-helpers/assets/79497/300d7b4d-96e1-4f42-bb3c-1af147858bae

**Comment by coopernewby** [comment]
This is super annoying and hard to debug. Is there any work around to make Invite user by email work with code exchange?

**Comment by tmountain** [comment]
I'm running into the same problem. There really needs to be a complete example regarding how to handle inbound requests from invite emails.

**Comment by silentworks** [comment]
@coopernewby @tmountain You can roll back to the previous version of the auth-helpers and this would work like how it was before but requires client side code to handle the auth token capture.

**Comment by bjarkebech** [comment]
Spent the entire day dealing with this issue and not even knowing what the root cause was. Had to break out the debugger and step through the code manually to determine that I indeed wasn't doing anything wrong on my end.

So basically, out of the box, there is NO way anymore to create a user and send them an invite link, since `inviteUserByEmail()` only supports the `implicit` auth flow. 

Two months ago, [auth-helpers dropped support for this flow](https://github.com/supabase/auth-helpers/blob/8c77550cd9eb2e57f160a126fe6236e6deaee504/packages/shared/src/createClient.ts#L30C21-L30C21), and yet there's [no mention of this in the official Supabase documentation](https://supabase.com/docs/reference/javascript/auth-admin-inviteuserbyemail) for this function.

I would really have appreciated a mention of this in the docs for `inviteUserByEmail()`, so I didn't have to go down this rabbit hole.

Anyway, this clunky workaround works for me:

`
const hashParams = new URLSearchParams(window.location.hash.substring(1));
const access_token = hashParams.get('access_token');
const refresh_token = hashParams.get('refresh_token');

const { data, error } = await supabase.auth.setSession({
  access_token,
  refresh_token,
});
`

**Comment by bjarkebech** [comment]
@silentworks can you confirm that you are working on implementing the PKCE flow for the magic link in `inviteUserByEmail()`?

If not, which other path would you suggest for inviting users by email?

**Comment by silentworks** [comment]
@bjarkebech yes this is being worked on. The screen recording above shows a working version, we just need to get some of these changes wrapped up in the CLI tool. This change will require a change to your email templates.

**Comment by takinola** [comment]
> Spent the entire day dealing with this issue and not even knowing what the root cause was. Had to break out the debugger and step through the code manually to determine that I indeed wasn't doing anything wrong on my end.
> 
> So basically, out of the box, there is NO way anymore to create a user and send them an invite link, since `inviteUserByEmail()` only supports the `implicit` auth flow.
> 
> Two months ago, [auth-helpers dropped support for this flow](https://github.com/supabase/auth-helpers/blob/8c77550cd9eb2e57f160a126fe6236e6deaee504/packages/shared/src/createClient.ts#L30C21-L30C21), and yet there's [no mention of this in the official Supabase documentation](https://supabase.com/docs/reference/javascript/auth-admin-inviteuserbyemail) for this function.
> 
> I would really have appreciated a mention of this in the docs for `inviteUserByEmail()`, so I didn't have to go down this rabbit hole.
> 
> Anyway, this clunky workaround works for me:
> 
> ```js
> const hashParams = new URLSearchParams(window.location.hash.substring(1));
> const access_token = hashParams.get('access_token');
> const refresh_token = hashParams.get('refresh_token');
> 
> const { data, error } = await supabase.auth.setSession({
>   access_token,
>   refresh_token,
> });
> ```

The issue with this approach is that the magic link does not expire after clicking on it.  The user can continue to click on it multiple times and be logged in automatically.  This may be a security risk in an application as anyone with future access to the invite email can log into the user's account.

**Comment by silentworks** [comment]
We have published a new guide on how to handle this from the email perspective and framework side of things. Note that this guide does not mention `supabase.auth.admin.generateLink()` but the same setup will still work. Here is a link from the part that you would need to follow https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr#create-api-endpoint-for-handling-tokenhash

If you are using the Supabase CLI and want to customize your email templates, you can do this now by following this guide https://supabase.com/docs/guides/cli/customizing-email-templates

**Comment by silentworks** [comment]
The guide above shows how to handle this issue and there is an example repo using this method so you can see it working https://github.com/silentworks/waiting-list. Closing this one out.
