### ISSUE TITLE
Next.js createServerComponentClient Dynamic server usage: cookies error when building with vercel

### ISSUE THREAD

**Issue by georgewritescode** [supabase/auth-helpers#570]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running vercel build, locally or on next.js I receive the following error.
It seems to be coming from the createServerComponentClient component from the error message.
Looks to be an issue when trying to build potentially without cookies present? (works fine in browser when generating on the fly)

```
Error: DynamicServerError: Dynamic server usage: cookies
    at staticGenerationBailout (/Users/user1/projects/ai/project1/.next/server/chunks/688.js:202:21)
    at Object.cookies (/Users/user1/projects/ai/project1/.next/server/chunks/688.js:94:62)
    at NextServerComponentAuthStorageAdapter.getCookie (/Users/user1/projects/ai/project1/.next/server/chunks/778.js:199:42)
    at NextServerComponentAuthStorageAdapter.getItem (/Users/user1/projects/ai/project1/.next/server/chunks/778.js:571:28)
    at /Users/user1/projects/ai/project1/.next/server/chunks/118.js:3004:37
    at Generator.next (<anonymous>)
    at /Users/user1/projects/ai/project1/.next/server/chunks/118.js:2912:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user1/projects/ai/project1/.next/server/chunks/118.js:2894:12)
    at getItemAsync (/Users/user1/projects/ai/project1/.next/server/chunks/118.js:3003:38) {
  digest: 'DYNAMIC_SERVER_USAGE'
  
```
This is my code:
Layout.ts
```
import Nav from './nav'
import { getSession } from '@/app/supabase-server';
import '@/styles/global.css'
import {redirect} from 'next/navigation'

export default async function DashboardLayout({
	children,
}: {
	children: React.ReactNode,
}) {
	const session = await getSession() || null;

	if (!session) {
		console.log("redirecting to sign in",session)
		redirect('/signin');
	}

	return <div>
		<div className='flex min-h-[720px]'>
			<div className='flex w-72 flex-col'>
				<Nav />
			</div>
			<div className='bg-slate-50 w-full min-h-screen'>
				<section>{children}</section>
			</div>
		</div>
	</div>;
}
```
supabase-server.ts
```
import { cookies } from 'next/headers';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { Database } from '@/types_db';

export const createServerSupabaseClient = () =>
  createServerComponentClient<Database>({ cookies });

export async function getSession() {
  const supabase = createServerSupabaseClient();
  try {
    const {
      data: { session }
    } = await supabase.auth.getSession();
    return session;
  } catch (error) {
    console.error('Error:', error);
    return null;
  }
}
```

## Expected behavior

Vercel builds properly

## System information

- OS: Mac
- Next 13.4.4
- Version of Node.js: 18
```
    "@supabase/supabase-js": "^2.23.0",
    "@supabase/auth-helpers-nextjs": "^0.7.0",
```

**Comment by dijonmusters** [comment]
Looks like this is just an error that is printed out to the console when Next.js detects that a page should be dynamically rendered - it uses `cookies` which is a Dynamic Function: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering#dynamic-functions

From my testing, and what I have read online, it looks like the build still succeeds and is likely something Next.js will supress in the future. But if you want to get rid of this console error, you can export a `dynamic` prop for the route.

```
export const dynamic = 'force-dynamic'
```

This flags that the route is intentionally dynamic, rather than Next.js detecting this via the usage of a Dynamic Function - cookies.

https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic

**Comment by Joshuajrodrigues** [comment]
Im currently having this same issue. I dont see anything logged locally but vercel fails to build.

I have a similar set up as the original poster. Wouldn't forcing dynamic on layout just force dynamic everywhere on the app ? Since the nav bar is basically used everywhere. I tried forcing it in thr navbar component only but that doesnt work, probably because its not a route.

**Comment by mrmartineau** [comment]
FYI while the fix outlined here might fix the issue, it does not work in all cases. There is a more reliable solution [on the next.js repo](https://github.com/vercel/next.js/issues/49373#issuecomment-1662263802) that recommends creating a reusable `createServerComponentClient` function that changes how `cookies` are used within the function. See below: 

```ts
import { createServerComponentClient as _createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { cache } from 'react';

import { Database } from '../types/supabase';

export const createServerComponentClient = cache(() => {
  const cookieStore = cookies();
  return _createServerComponentClient<Database>({ cookies: () => cookieStore });
});
```

Usage:

```ts
const supabaseClient = createServerComponentClient();
```

@dijonmusters do you think the docs and examples should be updated with this information?
